UPDWA/src/UPDWA/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UPDWA.Data;
using UPDWA.Models;

namespace UPDWA.Controllers
{
    public class AlertsController : Controller
    {
        private readonly AlertContext _context;

        public AlertsController(AlertContext context)
        {
            _context = context;    
        }

        // GET: Alerts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alerts.ToListAsync());
        }

        // GET: Alerts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alert = await _context.Alerts.SingleOrDefaultAsync(m => m.Id == id);
            if (alert == null)
            {
                return NotFound();
            }

            return View(alert);
        }

        // GET: Alerts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alerts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string AlertContent)
        {
            var Alert = new Alert
            {
                Message = AlertContent,
                FirstPosted = DateTime.Now,
                LastUpdated = DateTime.Now
            };
            if (ModelState.IsValid)
            {
                _context.Add(Alert);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(Alert);
        }

        // GET: Alerts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alert = await _context.Alerts.SingleOrDefaultAsync(m => m.Id == id);
            if (alert == null)
            {
                return NotFound();
            }
            return View(alert);
        }

        // POST: Alerts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstPosted,LastUpdated,Message")] Alert alert)
        {
            if (id != alert.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alert);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlertExists(alert.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(alert);
        }

        // GET: Alerts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alert = await _context.Alerts.SingleOrDefaultAsync(m => m.Id == id);
            if (alert == null)
            {
                return NotFound();
            }

            return View(alert);
        }

        // POST: Alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alert = await _context.Alerts.SingleOrDefaultAsync(m => m.Id == id);
            _context.Alerts.Remove(alert);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AlertExists(int id)
        {
            return _context.Alerts.Any(e => e.Id == id);
        }
    }
}

UPDWA/src/UPDWA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UPDWA.Data;

namespace UPDWA.Controllers
{
    public class HomeController : Controller
    {
        private readonly AlertContext _context;

        public HomeController(AlertContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.RecentAlerts = _context.Alerts.Where(x => x.FirstPosted >= DateTime.Now.AddDays(-5));
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

UPDWA/src/UPDWA/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>
    Sheriff Mike Hensley is currently serving as Sheriff for Unicoi County. Sheriff Hensley started his career in law enforcement in the 1970's. Sheriff Hensley has served under five sheriff
    administrations in Unicoi County and has worked with the Erwin Police Department being assigned to the 1st Judicial Drug Task Force. Sheriff Hensley served as Captain at the Criminal Investigation
    Division of the Unicoi County Sheriff's Department from 2003 to 2006. He was promoted to Chief Deputy in 2006 until 2010. Sheriff Hensley was reassigned to the Criminal Investigation Division in 2010
    as Investigator and 2nd shift supervisor until his appointment on March 26, 2012.
    <br />
    <br />
    <b>Staff:</b>
    <br />
    Frank Rodgers - Chief Deputy
    <br />
    Craig Masters - Administrative Assistant
    <br />
    Barbara Scalf - Jail Administrator
    <br />
    Ronnie Adkins - Chief Investigator
    <br />
    <br />
    <b>Office Hours:</b>
    <br />
    Administrative Offices: 8:30am - 4:30pm Monday-Friday
    <br />
    Deputies and Corrections Officers on duty 24 hours a day
    <br />
    <br />
    <b>Fees:</b>
    <br />
    Service of Process: $22.00
    <br />
    Service of Subpoena: $7.00
    <br />
    Work Release: $15.00 per day worked
    <br />
    <br />
    <b>Programs Offered by the Department:</b>
    <br />
    Neighborhood Watch Programs
    <br />
    Vial of Life
    <br />
    Senior Citizen Welfare Call Program
</p>

UPDWA/src/UPDWA/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<h2>@ViewData["Title"]</h2>

<address>
    1570 Jackson Love Hwy<br />
    P.O. Box 8<br />
    Erwin, TN 37650<br />
</address>

<address>
    <strong>Administration:</strong>423-743-1864<br />
    <strong>Jail:</strong>423-743-1858<br />
    <strong>Communication:</strong>423-743-1850
</address>

UPDWA/src/UPDWA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @section BeforeContainer{
        <div class="jumbotron jumbotron-fluid page-header">
            <div class="container">
                <h1>Unicoi County Police Department</h1>
                <span>Unicoi, TN</span>
        </div>
</div>
    }
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i> TN Highway Patrol Twitter</h4>
                </div>
                <div class="panel-body">
                    <a class="twitter-timeline" data-height="500" data-dnt="true" data-theme="light" href="https://twitter.com/TNHighwayPatrol?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">Tweets by Tennessee Highway Patrol</a>
                    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-gift"></i> Recent Alerts</h4>
                </div>
                <div class="panel-body">
                    @foreach(var Alert in ViewBag.RecentAlerts)
                    {
                        <div class="alert panel panel-default">
                            <div class="panel-body">
                                <i class="fa fa-clock-o" style="font-size: 0.9em;">Posted at @Alert.FirstPosted</i>
                                <p> <br />@Alert.Message</p>
                            </div>
                        </div>
                    }
                    <a asp-controller="Alerts" asp-action="Index" class="btn btn-default">View All</a>

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-compass"></i> Submit a Tip</h4>
                </div>
                <div class="panel-body">
                    <p>Submit an anonymous tip about a crime.</p>
                    <input type="text" placeholder="Tip..." /><br /><br />
                    <a href="#" class="btn btn-default">Submit</a>
                </div>
            </div>
        </div>
    </div>
        <!-- /.row -->
}